version: '3.8'

services:
  pocket-bar-postgres:
    container_name: eventimy-postgres
    image: postgres:latest
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: 10m
        max-file: '3'
    ports:
      - '5432:5432'
    volumes:
      - eventimy-postgres-volume:/var/lib/postgresql/data

volumes:
  eventimy-postgres-volume:
